# Generated by Django 3.2.13 on 2022-06-05 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=50, unique=True)),
                ('varietyprocess', models.CharField(max_length=50, unique=True)),
                ('flavournotes', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('approved', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='coffee_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
