# Generated by Django 3.2.13 on 2022-06-05 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='varietyprocess',
            new_name='process',
        ),
        migrations.AddField(
            model_name='post',
            name='variety',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
