# Generated by Django 3.2.13 on 2022-06-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0002_auto_20220605_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
    ]
