# Generated by Django 3.2.13 on 2022-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flavournotes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='process',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='variety',
            field=models.CharField(max_length=50),
        ),
    ]
