# Generated by Django 3.2.13 on 2022-06-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0005_auto_20220606_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='producer',
            field=models.CharField(max_length=50),
        ),
    ]
