# Generated by Django 4.1.1 on 2022-09-11 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_beans', '0006_alter_post_producer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Coffee',
        ),
    ]
