# Generated by Django 4.1.1 on 2022-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0007_rename_post_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
