# Generated by Django 4.1.1 on 2022-09-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0008_coffee_image_coffee_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['-region']},
        ),
    ]
