# Generated by Django 4.1.1 on 2022-09-11 18:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_beans', '0009_alter_coffee_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Coffees',
        ),
    ]
