# Generated by Django 4.1.1 on 2022-09-11 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_beans', '0010_rename_coffee_coffees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffees',
            new_name='Coffee',
        ),
    ]
