# Generated by Django 4.1.1 on 2022-09-13 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_beans', '0011_rename_coffees_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='coffee_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
