# Generated by Django 4.1.1 on 2022-09-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0012_alter_coffee_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='status',
        ),
    ]
