# Generated by Django 4.1.1 on 2022-09-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0014_alter_coffee_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['region']},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='image_url',
        ),
        migrations.AddField(
            model_name='coffee',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
