# Generated by Django 3.2.16 on 2022-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0015_alter_coffee_options_remove_coffee_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='entry_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
