# Generated by Django 3.2.16 on 2022-10-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_beans', '0016_coffee_entry_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='entry_number',
        ),
    ]
