# Generated by Django 3.2.16 on 2022-11-02 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee_beans', '0017_remove_coffee_entry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
